### PR TITLE
Note indicators indicate the wrong note

### LINKED ISSUE #319: Note indicators indicate the wrong note
When placed on a note with a fthora, the note indicator is supposed to indicate the virtual note (i.e., the note of the fthora) rather than the physical note. The software incorrectly displays the physical note.

From Kiltzanides' _Ecclesiastikon Apanthisma_:

indicator1

From _Mousikos Thisavros_:

indicator2

### PR DESCRIPTION
**Pull request by basil**
Fixes #319

### Testing done

indicator2

Koukouzelis Anoixantaria-1

### CODE REVIEW

File: src/services/LayoutService.ts [hunk 1]
```diff
@@ -1839,21 +1857,26 @@ export class LayoutService {
...
-      } else {
-        shift = fthora.startsWith('SoftChromaticThi') ? 0 : 1;
-      }
+      const fthoraNote = getScaleNoteValue(
+        chromaticFthoraNote ??
+          (fthora.startsWith('SoftChromaticPa') ? ScaleNote.Pa : ScaleNote.Thi),
+      );
+
+      shift = fthoraNote - currentNote;
+      shift = shift % 4;
```
Comment (basil) [inline src/services/LayoutService.ts:1879]: Also needed for (and present in) #322.

**Review by danielgarthur — APPROVED** [review]
